### ISSUE TITLE
Support Apple Silicon Docker Target

### ISSUE THREAD

**Issue by chris6647** [buildarr/buildarr#168]
Unable to pull from an Apple Silicon based machine as its not listed as a supported target. Gives error:
`no matching manifest for linux/arm64/v8 in the manifest list entries`
Adding:
`platform: linux/x86_64`
To the docker compose file seems to work as a workaround.

Thanks and keep up the good work! :)

**Comment by Callum027** [comment]
Hi there, thanks for trying Buildarr.

The Buildarr Docker images are automatically built and pushed using GitHub Actions. I don't have any Apple Silicon hardware to test on, but as Buildarr is written in Python, there is no reason why an ARM Docker image couldn't be built.

I'll have a look to see what I can do.

**Comment by Callum027** [comment]
Targets for `linux/arm/v7` and `linux/arm/v8` added via https://github.com/buildarr/buildarr-docker/commit/451da6abf4b67d7705dbbe5116b9765d62d45243.

Can you please try again using the ARM version?

**Comment by chris6647** [comment]
Was able to get a hold of a linux/arm64/v8 version, thanks a lot, and thanks even more so for the extremely fast support!

**Comment by Callum027** [comment]
Sorry, there was an issue with how I implemented the pipeline that meant only a 32-bit version of the `linux/arm/v8` container was available.

Can you try pulling again with the new (now confirmed 64-bit) version?

**Comment by chris6647** [comment]
I'm not sure how to verify that.

I no longer see a v8 here: https://hub.docker.com/layers/callum027/buildarr/latest/images/sha256-a2cc88001a89d506caffe98807a1bda048a5ef05559060c7ab09829c97dc2b9d?context=explore
and the sha digest I'm seeing locally doesnt match this.
And my local image inspect of the image also just says:
```
 "Architecture": "arm64",
        "Os": "linux",
```
With no mention of the v8 anywhere. But the docker-desktop still doesnt complain about wrong arch (which is that it did originally when i opened the issue)

**Comment by Callum027** [comment]
The platform name for 32-bit ARMv8 is `linux/arm/v8`, and the platform name for 64-bit ARMv8 is `linux/arm64`, which is why you're not seeing `v8` in the metadata.

If the architecture you're seeing is `arm64`, then there are no issues. Thanks for verifying!
